---
abstract: 'recursive DNS zone walk'
author:
  - 'Karl Gaissmaier <gaissmai(at)cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DNS-Zonewalk
provides:
  App::DNS::Zonewalk:
    file: lib/App/DNS/Zonewalk.pm
    version: 0.03
requires:
  Net::DNS: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
